-- Active: 1688906947613@@127.0.0.1@5432@avalia_ai
CREATE OR REPLACE PROCEDURE InsertFromCSV(path TEXT, table_name TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
    EXECUTE format('COPY %I FROM %L DELIMITER %L CSV HEADER', table_name, path, ',');
END $$;

do $$
declare
   data_path VARCHAR := '/mnt/d/Users/rafae/Área de Trabalho/UnB/Matérias/8° Semestre/BD - Bancos de Dados/Trabalho/data/';
   tmp text;
begin

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "User" (
  "id" char(9) UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL CHECK (name <> ''),
  "course" varchar NOT NULL CHECK (course <> ''),
  "is_admin" boolean NOT NULL DEFAULT false,
  "email" varchar(50) UNIQUE NOT NULL CHECK (email <> ''),
  "password" varchar(50) NOT NULL CHECK (password <> '')
);

CREATE TABLE "Comment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "body" text,
  "rating" integer NOT NULL CHECK (rating >= 0 AND rating <= 5),
  "user_id" char(9) NOT NULL,
  "class_id" integer NOT NULL
);

CREATE TABLE "Report" (
  "comment_id" integer NOT NULL,
  "user_id" char(9) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "comment_id")
);

CREATE TABLE "Subject" (
  "code" varchar(30) UNIQUE PRIMARY KEY NOT NULL CHECK (code <> ''),
  "name" varchar(200) NOT NULL CHECK (name <> ''),
  "department_code" varchar(5) NOT NULL
);

CREATE TABLE "Department" (
  "name" varchar(200) NOT NULL CHECK (name <> ''),
  "code" varchar(5) UNIQUE PRIMARY KEY NOT NULL CHECK (code <> '')
);

CREATE TABLE "Teacher" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(100) NOT NULL CHECK (name <> ''),
  "department_code" varchar(5) NOT NULL
);

CREATE TABLE "Class" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "total_spots" varchar(3) CHECK (total_spots <> ''),
  "enrolled_students" varchar(3) CHECK (enrolled_students <> ''),
  "location" varchar CHECK (location <> ''),
  "schedule" varchar CHECK (schedule <> ''),
  "period" char(6) NOT NULL CHECK (period <> ''),
  "number" varchar(30) NOT NULL CHECK (number <> ''),
  "teacher_id" integer NOT NULL,
  "subject_code" varchar(30) NOT NULL
);

CREATE TABLE "Authentication" (
  "token" UUID UNIQUE PRIMARY KEY NOT NULL DEFAULT (uuid_generate_v4()),
  "user_id" char(9) NOT NULL
);

ALTER TABLE "Comment" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Report" ADD FOREIGN KEY ("comment_id") REFERENCES "Comment" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Report" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Comment" ADD FOREIGN KEY ("class_id") REFERENCES "Class" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Subject" ADD FOREIGN KEY ("department_code") REFERENCES "Department" ("code") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Teacher" ADD FOREIGN KEY ("department_code") REFERENCES "Department" ("code") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Class" ADD FOREIGN KEY ("teacher_id") REFERENCES "Teacher" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Class" ADD FOREIGN KEY ("subject_code") REFERENCES "Subject" ("code") ON DELETE CASCADE ON UPDATE CASCADE;


CREATE OR REPLACE VIEW "SubjectView" AS
SELECT s.code, s.name, d.name AS department_name
FROM "Subject" AS s
LEFT JOIN "Department" AS d
ON s.department_code = d.code;

CREATE OR REPLACE VIEW "TeacherView" AS
SELECT id, t.name, d.name AS department_name
FROM "Teacher" AS t
LEFT JOIN "Department" AS d
ON t.department_code = d.code;

CALL InsertFromCSV(data_path || 'departamentos.csv', 'Department');
CALL InsertFromCSV(data_path || 'disciplinas.csv', 'Subject');
CALL InsertFromCSV(data_path || 'professores.csv', 'Teacher');
CALL InsertFromCSV(data_path || 'turmas.csv', 'Class');

INSERT INTO "Department" (name, code)
VALUES ('Departamento1', '00000'),
       ('Departamento2', '00001'),
       ('Departamento3', '00002'),
       ('Departamento4', '00003');

INSERT INTO "Subject" (code, name, department_code)
VALUES ('XXXXXX', 'Disciplina1', '00000'),
       ('YYYYYY', 'Disciplina2', '00001'),
       ('ZZZZZZ', 'Disciplina3', '00002'),
       ('JJJJJJ', 'Disciplina4', '00003');

SELECT setval((SELECT PG_GET_SERIAL_SEQUENCE('"Teacher"', 'id')), (SELECT MAX(id) FROM "Teacher") + 1) INTO tmp;

INSERT INTO "Teacher" (name, department_code)
VALUES ('Professor1', '00000'),
       ('Professor2', '00001'),
       ('Professor3', '00002'),
       ('Professor4', '00003');

SELECT setval((SELECT PG_GET_SERIAL_SEQUENCE('"Class"', 'id')), (SELECT MAX(id) FROM "Class") + 1) INTO tmp;

INSERT INTO "Class" (total_spots, enrolled_students, location, schedule,  period,  number,  teacher_id,  subject_code)
SELECT '10', '10', 'Local1', 'Horario1', 'aaaa.1', '1', id, 'XXXXXX' FROM "Teacher" WHERE "name" = 'Professor1' AND "department_code" = '00000'
UNION ALL
SELECT '10', '10', 'Local2', 'Horario2', 'aaaa.2', '2', id, 'YYYYYY' FROM "Teacher" WHERE "name" = 'Professor2' AND "department_code" = '00001'
UNION ALL
SELECT '10', '10', 'Local3', 'Horario3', 'aaaa.3', '3', id, 'ZZZZZZ' FROM "Teacher" WHERE "name" = 'Professor3' AND "department_code" = '00002'
UNION ALL
SELECT '10', '10', 'Local4', 'Horario4', 'aaaa.4', '4', id, 'JJJJJJ' FROM "Teacher" WHERE "name" = 'Professor4' AND "department_code" = '00003';

INSERT INTO "User" (id, name, course, is_admin, email, password)
VALUES ('190134780', 'Rafael', 'Engenharia de Computação', true, '190134780@aluno.unb.br', '12345678'),
       ('200000000', 'Admin', 'Engenharia de Computação', true, '200000000@aluno.unb.br', '12345678'),
       ('210000000', 'Aluno', 'Engenharia de Computação', false, '210000000@aluno.unb.br', '12345678');

INSERT INTO "Comment" (body, rating, user_id, class_id)
SELECT 'Comentario', 5, '190134780', id FROM "Class" WHERE teacher_id IN (SELECT id FROM "Teacher" WHERE "name" = 'Professor1' AND "department_code" = '00000')
UNION ALL
SELECT 'Comentario', 4, '200000000', id FROM "Class" WHERE teacher_id IN (SELECT id FROM "Teacher" WHERE "name" = 'Professor2' AND "department_code" = '00001')
UNION ALL
SELECT 'Comentario', 3, '210000000', id FROM "Class" WHERE teacher_id IN (SELECT id FROM "Teacher" WHERE "name" = 'Professor3' AND "department_code" = '00002');

INSERT INTO "Report" (comment_id, user_id)
SELECT id, '210000000' FROM "Comment" WHERE user_id = '200000000'
UNION ALL
SELECT id, '200000000' FROM "Comment" WHERE user_id = '210000000'
UNION ALL
SELECT id, '210000000' FROM "Comment" WHERE user_id = '190134780';

RETURN;

end $$;
